### ISSUE TITLE
안녕하세요 다운 오류 관련 질문입니다.

### ISSUE THREAD

**Issue by RappidStar** [dc-koromo/hitomi-downloader-2#10]
![1](https://user-images.githubusercontent.com/40864445/42331478-73f1b768-80b0-11e8-8e03-4072de238c5d.png)

다운 누르면 이런 메시지가 뜨는데
계속을 누르면 다운이 안되고 끝내기를 누르면 프로그램이 종료됩니다...

**Comment by dc-koromo** [comment]
굉장히 오래된 희귀한 유물이군요

https://github.com/dc-koromo/hitomi-downloader-2/releases/tag/3.30

이걸 사용하세요

**Comment by dc-koromo** [comment]
그리고 제 메일 koromo.software@gmail.com 으로 언제들이 메일주세염 ~

**Comment by RappidStar** [comment]
아이고~ 제가 오래된 유물을 쓰고 있었군요;;;
최신문물 잘 받습니다
감사해요
