### ISSUE TITLE
이따금 다운안되는 자료들로 인해서 다운로드가 먹통되는데요

### ISSUE THREAD

**Issue by A2Ring** [dc-koromo/hitomi-downloader-2#2]
![image](https://user-images.githubusercontent.com/28779061/38911516-e5523ea2-430a-11e8-806a-da39cfaa3fd7.png)
이런식으로 되는데.
해당 파일 다운로드 취소나 삭제기능은 추가될수없나요?
아무리 시간지나도 안받아지다보니 
매번 이러면 종료하고 다시 켜는 방법밖에 없어서...

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/hitomi-downloader-2/commit/61fd6aec41c8eda5f6131ea77766366a8c2b6901
해당 기능을 추가했습니다.
