### ISSUE TITLE
설정중 모든언어로 한후 검색할시 해당작품이 어떤 언어인지 알려줬으면 좋겠습니다

### ISSUE THREAD

**Issue by YTOAA** [dc-koromo/hitomi-downloader-2#9]
건의사항이긴 합니다만 그런 기능이 추가되었으면 ..

**Comment by dc-koromo** [comment]
https://github.com/dc-koromo/hitomi-downloader-2/commit/109eac1c30aec2390607e5f0305f8a0fb5fd1ba3

추가됨
